/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ACard: typeof import('./components/ACard.vue')['default']
    Dashboard: typeof import('./components/Dashboard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Widget: typeof import('./components/Widget.vue')['default']
    WidgetView: typeof import('./components/WidgetView.vue')['default']
  }
}
